export enum ResCode {
    CONTINUE = 100,
    SWITCHING_PROTOCOLS = 101,
    PROCESSING = 102,
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NON_AUTHORITATIVE_INFORMATION = 203,
    NO_CONTENT = 204,
    RESET_CONTENT = 205,
    PARTIAL_CONTENT = 206,
    MULTI_STATUS = 207,
    ALREADY_REPORTED = 208,
    IM_USED = 226,
    MULTIPLE_CHOICES = 300,
    MOVED_PERMANENTLY = 301,
    FOUND = 302,
    SEE_OTHER = 303,
    NOT_MODIFIED = 304,
    USE_PROXY = 305,
    TEMPORARY_REDIRECT = 307,
    PERMANENT_REDIRECT = 308,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    PAYMENT_REQUIRED = 402,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    METHOD_NOT_ALLOWED = 405,
    NOT_ACCEPTABLE = 406,
    PROXY_AUTHENTICATION_REQUIRED = 407,
    REQUEST_TIMEOUT = 408,
    CONFLICT = 409,
    GONE = 410,
    LENGTH_REQUIRED = 411,
    PRECONDITION_FAILED = 412,
    PAYLOAD_TOO_LARGE = 413,
    REQUEST_URI_TOO_LONG = 414,
    UNSUPPORTED_MEDIA_TYPE = 415,
    REQUESTED_RANGE_NOT_SATISFIABLE = 416,
    EXPECTATION_FAILED = 417,
    I_M_A_TEAPOT = 418,
    MISDIRECTED_REQUEST = 421,
    UNPROCESSABLE_ENTITY = 422,
    LOCKED = 423,
    FAILED_DEPENDENCY = 424,
    UPGRADE_REQUIRED = 426,
    PRECONDITION_REQUIRED = 428,
    TOO_MANY_REQUESTS = 429,
    REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
    CONNECTION_CLOSED_WITHOUT_RESPONSE = 444,
    UNAVAILABLE_FOR_LEGAL_REASONS = 451,
    CLIENT_CLOSED_REQUEST = 499,
    INTERNAL_SERVER_ERROR = 500,
    NOT_IMPLEMENTED = 501,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
    GATEWAY_TIMEOUT = 504,
    HTTP_VERSION_NOT_SUPPORTED = 505,
    VARIANT_ALSO_NEGOTIATES = 506,
    INSUFFICIENT_STORAGE = 507,
    LOOP_DETECTED = 508,
    NOT_EXTENDED = 510,
    NETWORK_AUTHENTICATION_REQUIRED = 511,
    NETWORK_CONNECT_TIMEOUT_ERROR = 599
}

export const RESPONSE_MESSAGE: any = {
    [ResCode.CONTINUE]: "Continue",
    [ResCode.SWITCHING_PROTOCOLS]: "Switching Protocols",
    [ResCode.PROCESSING]: "Processing",
    [ResCode.OK]: "OK",
    [ResCode.CREATED]: "Created",
    [ResCode.ACCEPTED]: "Accepted",
    [ResCode.NON_AUTHORITATIVE_INFORMATION]: "Non-authoritative Information",
    [ResCode.NO_CONTENT]: "No Content",
    [ResCode.RESET_CONTENT]: "Reset Content",
    [ResCode.PARTIAL_CONTENT]: "Partial Content",
    [ResCode.MULTI_STATUS]: "Multi-Status",
    [ResCode.ALREADY_REPORTED]: "Already Reported",
    [ResCode.IM_USED]: "IM Used",
    [ResCode.MULTIPLE_CHOICES]: "Multiple Choices",
    [ResCode.MOVED_PERMANENTLY]: "Moved Permanently",
    [ResCode.FOUND]: "Found",
    [ResCode.SEE_OTHER]: "See Other",
    [ResCode.NOT_MODIFIED]: "Not Modified",
    [ResCode.USE_PROXY]: "Use Proxy",
    [ResCode.TEMPORARY_REDIRECT]: "Temporary Redirect",
    [ResCode.PERMANENT_REDIRECT]: "Permanent Redirect",
    [ResCode.BAD_REQUEST]: "Bad Request",
    [ResCode.UNAUTHORIZED]: "Unauthorized",
    [ResCode.PAYMENT_REQUIRED]: "Payment Required",
    [ResCode.FORBIDDEN]: "Forbidden",
    [ResCode.NOT_FOUND]: "Not Found",
    [ResCode.METHOD_NOT_ALLOWED]: "Method Not Allowed",
    [ResCode.NOT_ACCEPTABLE]: "Not Acceptable",
    [ResCode.PROXY_AUTHENTICATION_REQUIRED]: "Proxy Authentication Required",
    [ResCode.REQUEST_TIMEOUT]: "Request Timeout",
    [ResCode.CONFLICT]: "Conflict",
    [ResCode.GONE]: "Gone",
    [ResCode.LENGTH_REQUIRED]: "Length Required",
    [ResCode.PRECONDITION_FAILED]: "Precondition Failed",
    [ResCode.PAYLOAD_TOO_LARGE]: "Payload Too Large",
    [ResCode.REQUEST_URI_TOO_LONG]: "Request-URI Too Long",
    [ResCode.UNSUPPORTED_MEDIA_TYPE]: "Unsupported Media Type",
    [ResCode.REQUESTED_RANGE_NOT_SATISFIABLE]: "Requested Range Not Satisfiable",
    [ResCode.EXPECTATION_FAILED]: "Expectation Failed",
    [ResCode.I_M_A_TEAPOT]: "I'm a teapot",
    [ResCode.MISDIRECTED_REQUEST]: "Misdirected Request",
    [ResCode.UNPROCESSABLE_ENTITY]: "Unprocessable Entity",
    [ResCode.LOCKED]: "Locked",
    [ResCode.FAILED_DEPENDENCY]: "Failed Dependency",
    [ResCode.UPGRADE_REQUIRED]: "Upgrade Required",
    [ResCode.PRECONDITION_REQUIRED]: "Precondition Required",
    [ResCode.TOO_MANY_REQUESTS]: "Too Many Requests",
    [ResCode.REQUEST_HEADER_FIELDS_TOO_LARGE]: "Request Header Fields Too Large",
    [ResCode.CONNECTION_CLOSED_WITHOUT_RESPONSE]: "Connection Closed Without Response",
    [ResCode.UNAVAILABLE_FOR_LEGAL_REASONS]: "Unavailable For Legal Reasons",
    [ResCode.CLIENT_CLOSED_REQUEST]: "Client Closed Request",
    [ResCode.INTERNAL_SERVER_ERROR]: "Internal Server Error",
    [ResCode.NOT_IMPLEMENTED]: "Not Implemented",
    [ResCode.BAD_GATEWAY]: "Bad Gateway",
    [ResCode.SERVICE_UNAVAILABLE]: "Service Unavailable",
    [ResCode.GATEWAY_TIMEOUT]: "Gateway Timeout",
    [ResCode.HTTP_VERSION_NOT_SUPPORTED]: "HTTP Version Not Supported",
    [ResCode.VARIANT_ALSO_NEGOTIATES]: "Variant Also Negotiates",
    [ResCode.INSUFFICIENT_STORAGE]: "Insufficient Storage",
    [ResCode.LOOP_DETECTED]: "Loop Detected",
    [ResCode.NOT_EXTENDED]: "Not Extended",
    [ResCode.NETWORK_AUTHENTICATION_REQUIRED]: "Network Authentication Required",
    [ResCode.NETWORK_CONNECT_TIMEOUT_ERROR]: "Network Connect Timeout Error"
}
